music.setTempo(60)
music.playTone(330, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Quarter))
music.playTone(587, music.beat(BeatFraction.Quarter))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(659, music.beat(BeatFraction.Eighth))
music.playTone(698, music.beat(BeatFraction.Quarter))
music.playTone(698, music.beat(BeatFraction.Quarter))
music.playTone(659, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(659, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(587, music.beat(BeatFraction.Quarter))
music.playTone(659, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Eighth))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(440, music.beat(BeatFraction.Quarter))
basic.forever(function () {
	
})
